package com.mdev.chatapp.ui.auth

sealed class AuthUiEvent {
    data class UsernameChanged(val value: String): AuthUiEvent()
    data class PasswordChanged(val value: String): AuthUiEvent()
    data class RePasswordChanged(val value: String) : AuthUiEvent()
    data class EmailChanged(val value: String): AuthUiEvent()
    data class SignedInUsernameChanged(val value: String): AuthUiEvent()
    data class DeleteUserChanged(val value: String): AuthUiEvent()
    data class UnAuthenticatedUserChanged(val username: String): AuthUiEvent()
    data class OTPChanged(val value: String): AuthUiEvent()
    data object ResetPassword: AuthUiEvent()
    data object SignIn: AuthUiEvent()
    data object SignUp: AuthUiEvent()
    data object Authenticated: AuthUiEvent()
    data object SignedIn: AuthUiEvent()
    data object SendOTP: AuthUiEvent()
    data object SendResetPasswordOTP: AuthUiEvent()
    data object VerifyResetPasswordOTP: AuthUiEvent()
    data object ResetState: AuthUiEvent()
    data object CancelResetPassword: AuthUiEvent()
    data object ForgotPassword: AuthUiEvent()
    data object BackToInputEmailClick: AuthUiEvent()
    data object BackToSignInClick: AuthUiEvent()
    data object BackToSignUpClick: AuthUiEvent()
}